### ISSUE TITLE
How are you getting the details from kerala vision?

### ISSUE THREAD

**Issue by vajahath** [richardjoy530/Broadband#3]
I'm interested in porting this functionality into an npm module.
Could you please explain how you are getting these info? Are there any APIs for this?

**Comment by richardjoy530** [comment]
Well, I'm actually calling the GET/POST requests manually and parsing the result. Those APIs are called by keralalavision website under the hood. You can find it by doing an inspection on the network tab 
![image](https://user-images.githubusercontent.com/11271119/137065534-6576d96a-c4aa-4d24-8fe2-02f7c34a1dfe.png)


Hope this helped :)

**Comment by richardjoy530** [comment]
https://github.com/richardjoy530/Broadband/blob/14447894254d455f5f3d88c670386ea30ad6f08d/lib/main.dart#L246
